### ISSUE TITLE
not working in --prod --release mode

### ISSUE THREAD

**Issue by lovepreetintugine** [eakoriakin/ionic-select-searchable#12]
hi,
Its working fine in debug mode but when i generate app in prod mode then select searchable plugin not working. nothing open on click select box field
when i am using 
ionic cordova build android -debug
then working fine for me.
but using
 ionic build android --prod --release
its not working

**Comment by eakoriakin** [comment]
Hey @lovepreetintugine, for some reason running a build with --prod flag throws an error.
I'll try ti fix it later, when I have some time.
For now, can you use just --release flag, which should work fine?

**Comment by lovepreetintugine** [comment]
hi  Evgenii Koriakin

Thanks for reply . Its working fine in release mode.
when you resolve this issue then ping me once

*Thanks*

On Sun, Mar 11, 2018 at 12:41 PM, Evgenii Koriakin <notifications@github.com

**Comment by whyike** [comment]
any news? me is also waiting for this fix.

**Comment by eakoriakin** [comment]
Hi, no news yet unfortunately. I’ll try to find some time to fix it next week.

**Comment by rohitbhatnagar85** [comment]
Looking forward to the fix @eakoriakin :) Thanks!

**Comment by netidjen** [comment]
Hi guys, any of you found the solutions for this issue? I just try to update the select component to the latest version. But,still not working.

**Comment by jingglang** [comment]
This fix works for me. Add this line to index.ts and rebuild:

`export { SelectSearchablePage } from './select-searchable-page.component';`

**Comment by eakoriakin** [comment]
Hi @jingglang, where should I put it? To `\ionic-select-searchable\src\index.ts`?

**Comment by jingglang** [comment]
@eakoriakin exactly. At the moment only SelectSearchable is exported. We need to to export SelectSearchablePage as well.

**Comment by eakoriakin** [comment]
Hey @lovepreetintugine, @whyike, @rohitbhatnagar85, @netidjen. Guys can you try `1.0.14` version? Let me know if it works for you.

**Comment by jingglang** [comment]
@eakoriakin  `1.0.14` works great. Thank you for this awesome component.

**Comment by eakoriakin** [comment]
@jingglang thank you for saving me time with this excellent hint! 🙂

**Comment by jessicastorm1986** [comment]
giving me error - ionic-select-searchable/ionic-select-searchable.d.ts, found version 4, expected 3 i have installed npm install ionic-select-searchable@latest --save , please advise

**Comment by jessicastorm1986** [comment]
This is my package.json -

```
{
  "_from": "ionic-select-searchable@latest",
  "_id": "ionic-select-searchable@1.0.16",
  "_inBundle": false,
  "_integrity": "sha512-VMyPqEGOBZXSkCCpOGsXVllwyWlwccqEC7vJ18EPHtSEe5yZxzWLnarLFQPoctdMsRmdjvUDvFpcn08UEE2HYw==",
  "_location": "/ionic-select-searchable",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "ionic-select-searchable@latest",
    "name": "ionic-select-searchable",
    "escapedName": "ionic-select-searchable",
    "rawSpec": "latest",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/ionic-select-searchable/-/ionic-select-searchable-1.0.16.tgz",
  "_shasum": "48bf20a529f73b261cbfe8309fcf032c88d68c4e",
  "_spec": "ionic-select-searchable@latest",
  "_where": "F:\\D\\IONIC\\quicktask\\quicktask-20march\\quicktask",
  "author": {
    "name": "Evgenii Koriakin",
    "url": "https://github.com/eakoriakin"
  },
  "bugs": {
    "url": "https://github.com/eakoriakin/ionic-select-searchable/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "An Ionic component similar to ion-select, that allows to search items, including async search and infinite scrolling.",
  "homepage": "https://github.com/eakoriakin/ionic-select-searchable#readme",
  "keywords": [
    "ionic",
    "ionic 2",
    "ion-select",
    "search",
    "searchable",
    "searchbar",
    "select"
  ],
  "main": "ionic-select-searchable.umd.js",
  "module": "ionic-select-searchable.js",
  "name": "ionic-select-searchable",
  "peerDependencies": {
    "@angular/core": ">=4.1.3",
    "ionic-angular": ">=3.6.0",
    "rxjs": ">=5.4.0",
    "zone.js": ">=0.8.12"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/eakoriakin/ionic-select-searchable.git"
  },
  "title": "Ionic Select with Searchbar",
  "typings": "ionic-select-searchable.d.ts",
  "version": "1.0.16"
}

```

**Comment by rlmax** [comment]
any update ... waiting prod mode

**Comment by jingglang** [comment]
@rlmax what version are you at? 1.0.14 works for me.

**Comment by mrsergejl** [comment]
I have same "found version 4, expected 3" error. That is very unfortunate as I am standing a few days before planned release. Is there maybe a "dirty hack" method available ?

**Comment by niyasheraf** [comment]
Got a fix. 

re-import in the module in which we are using the plugin and include it in the import array.

**Comment by eakoriakin** [comment]
Hi @niyasheraf, thanks for the fix!
So, you have multiple modules, and you import `SelectSearchableModule` to each of them, right?

**Comment by niyasheraf** [comment]
@eakoriakin Exactly. Hope it will work so.

**Comment by kuldeepsingh99** [comment]
I am also getting this error while  trying to build    
ionic build android --prod --release 
/ionic-select-searchable.d.ts, found version 4, expected 3

Please help on this 
```
{
  "name": "Test",
  "version": "0.0.1",
  "author": "",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "^4.4.7",
    "@angular/compiler": "^4.4.7",
    "@angular/compiler-cli": "^4.4.7",
    "@angular/core": "^4.4.7",
    "@angular/forms": "^4.4.7",
    "@angular/http": "^4.4.7",
    "@angular/platform-browser": "^4.4.7",
    "@angular/platform-browser-dynamic": "^4.4.7",
    "@ionic-native/core": "^3.14.0",
    "@ionic-native/date-picker": "^4.7.0",
    "@ionic-native/splash-screen": "^3.14.0",
    "@ionic-native/status-bar": "^3.14.0",
    "@ionic/storage": "^2.0.1",
    "angular2-jwt": "^0.2.3",
    "cordova-android": "^6.2.3",
    "cordova-plugin-compat": "^1.0.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-sqlite-storage": "^2.0.4",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic-select-searchable": "^2.7.0",
    "ionic2-super-tabs": "^4.2.2",
    "ionicons": "^3.0.0",
    "rxjs": "^5.5.11",
    "sw-toolbox": "^3.6.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.4",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-geolocation": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

**Comment by eakoriakin** [comment]
Hey @kuldeepsingh99, check out [demo](https://github.com/eakoriakin/ionic-select-searchable-demo) app and try to find what is different in your configuration.

Try maybe to install a newer version of `typescript`, say `2.9.1`.

**Comment by fradali** [comment]
Hello,
Please can someone provide us with the right solution and how to do it ? and thanks
