### ISSUE TITLE
item.object.value?

### ISSUE THREAD

**Issue by silco** [eakoriakin/ionic-select-searchable#13]
hi ,It's working fine , how can i do :  itemTextField= object.value (item.address.street) ?
thanks.

**Comment by eakoriakin** [comment]
Hey, use “itemTemplate” for complex title

**Comment by silco** [comment]
Hi, do you mean itemTemplate="address.street" ? 

Thanks .

**Comment by eakoriakin** [comment]
Nope, can you check the docs from read me? There should be a sample

**Comment by eakoriakin** [comment]
getItemTemplate(item) {
  return item.address.street;
}

HTML:
itemTemplate=“getItemTemplate”

**Comment by eakoriakin** [comment]
Have a look at the docs as well:
https://github.com/eakoriakin/ionic-select-searchable/wiki/API-Documentation#itemtemplate
