### ISSUE TITLE
How to change the infinite scrolling value?

### ISSUE THREAD

**Issue by Diego74965** [eakoriakin/ionic-select-searchable#14]
Let's say i want it to be 50 then 50, not 100 then 100

**Comment by eakoriakin** [comment]
Do yo mean you want to change the number of items loaded on scrolling? I’m first scroll it loads 50, then 100? Am I right?

**Comment by eakoriakin** [comment]
Also, have a look at `home.ts` file in `ionic-select-searchable-demo` repository.

```
getMorePorts(event: { component: SelectSearchable, infiniteScroll: InfiniteScroll }) {
  ...
  // This method simulates backend pagination.
  this.portService.getPortsAsync(this.ports10Page).subscribe(ports => {
    ..
  }
}
```
