### ISSUE TITLE
change text "clear" in button used for canReset

### ISSUE THREAD

**Issue by strogof** [eakoriakin/ionic-select-searchable#17]
Hi eakoriakin,
thanks for sharing your excellent work
it's not an issue,
can you, please, tell me how to change the text "clear" in something else ?

**Comment by eakoriakin** [comment]
Hey, I've added `resetButtonText` option:
https://github.com/eakoriakin/ionic-select-searchable/wiki/API-Documentation#resetbuttontext

Please, update to `1.0.11` version.

**Comment by strogof** [comment]
Tanks again

Il giorno dom 25 mar 2018 alle 08:00 Evgenii Koriakin <
notifications@github.com> ha scritto:

**Comment by eakoriakin** [comment]
no problem 🙂
