### ISSUE TITLE
 Shouldn't use NavController to push a new View

### ISSUE THREAD

**Issue by luckyboykg** [eakoriakin/ionic-select-searchable#23]
If you use NavController to push a new View, IONIC will treat this behavior like we change the View, the ionViewCanLeave will trigger.

It's not make sense for this case, we just open a dialog to choose some items and we don't want to push the new View.

When I need to check the Form is dirty or not I met this issues :
The event ionViewCanLeave will trigger every time this control opened.

My solution is : change from NavController to Modal dialog.

**Comment by eakoriakin** [comment]
Hi, I see... It seems like it would be better to use `Modal` rather than `Page`. I'll try to find some time to implement it.

**Comment by eakoriakin** [comment]
@GFoley83 thanks a lot for the PR, it saved me time 👍 

Version `1.1.1` now has `useModal` parameter with `true` as default value:
https://github.com/eakoriakin/ionic-select-searchable/wiki/API-Documentation#usemodal
