### ISSUE TITLE
Code console logs

### ISSUE THREAD

**Issue by CatalinZoicas** [eakoriakin/ionic-select-searchable#24]
Found this console logs in the plugin.
Could this 2 lines be deleted?

https://github.com/eakoriakin/ionic-select-searchable/blob/cdaab53fe3818c2270fd9b7ff839a3b0f011e684/src/select-searchable.component.ts#L165
https://github.com/eakoriakin/ionic-select-searchable/blob/cdaab53fe3818c2270fd9b7ff839a3b0f011e684/src/select-searchable.component.ts#L166

Thanks .

**Comment by eakoriakin** [comment]
Hey, good catch, forgot to remove it after doing some debugging.
Removed in 1.0.17.
