### ISSUE TITLE
Can't bind to 'items' since it isn't a known property of 'select-searchable'

### ISSUE THREAD

**Issue by biswadeep-sarkar** [eakoriakin/ionic-select-searchable#25]
```
Template parse errors:
Can't bind to 'items' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
							itemValueField="id"
							itemTextField="name"
							[ERROR -&gt;][items]="ports"
							[canSearch]="true"
							(onChange)="portChange($event)"&gt;
"): ng:///HiremePageModule/HiremePage.html@46:7
Can't bind to 'canSearch' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'canSearch' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
							itemTextField="name"
							[items]="ports"
							[ERROR -&gt;][canSearch]="true"
							(onChange)="portChange($event)"&gt;
						&lt;/select-searchable&gt;
"): ng:///HiremePageModule/HiremePage.html@47:7
'select-searchable' is not a known element:
1. If 'select-searchable' is an Angular component, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
					&lt;/ion-item-divider&gt;
					&lt;ion-item&gt;
						[ERROR -&gt;]&lt;select-searchable
							[(ngModel)]="port3"
							title="Port"
"): ng:///HiremePageModule/HiremePage.html@41:6
```

`Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
							itemValueField="id"
							itemTextField="name"
							[ERROR ->][items]="ports"
							[canSearch]="true"
							(onChange)="portChange($event)">
"): ng:///HiremePageModule/HiremePage.html@46:7
Can't bind to 'canSearch' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'canSearch' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
							itemTextField="name"
							[items]="ports"
							[ERROR ->][canSearch]="true"
							(onChange)="portChange($event)">
						</select-searchable>
"): ng:///HiremePageModule/HiremePage.html@47:7
'select-searchable' is not a known element:
1. If 'select-searchable' is an Angular component, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
					</ion-item-divider>
					<ion-item>
						[ERROR ->]<select-searchable
							[(ngModel)]="port3"
							title="Port"
"): ng:///HiremePageModule/HiremePage.html@41:6
    at syntaxError (http://localhost:8100/build/vendor.js:82258:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:106121:19)
    at JitCompiler._parseTemplate (http://localhost:8100/build/vendor.js:115549:37)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:115524:23)
    at http://localhost:8100/build/vendor.js:115426:62
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:115426:19)
    at http://localhost:8100/build/vendor.js:115296:19
    at Object.then (http://localhost:8100/build/vendor.js:82247:77)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:115295:26)`

Ionic Version:

> Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.4.0
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by eakoriakin** [comment]
Hi, you are probably using lazy loading. Have a look here:
https://github.com/eakoriakin/ionic-select-searchable#1-why-do-i-get-error-cant-bind-to-items-since-it-isnt-a-known-property-of-select-searchable

**Comment by eakoriakin** [comment]
Then check that you've imported `SelectSearchableModule` to your main `AppModule`:

```
import { NgModule } from '@angular/core';
import { SelectSearchableModule } from 'ionic-select-searchable';

@NgModule({
    ...
    imports: [
        ...
        SelectSearchableModule
    ],
    ...
})
export class AppModule { }
```

**Comment by eakoriakin** [comment]
@biswadeep-sarkar have a look here as well:
https://github.com/eakoriakin/ionic-select-searchable-demo/issues/12#issuecomment-377646075

**Comment by cerge** [comment]
Sorry, i have the same issue in ionic 3 but using the main example. I have all the imports fine. I tried to follow the link below but it was removed.

**Comment by eakoriakin** [comment]
Check this link:
https://github.com/eakoriakin/ionic-selectable/wiki#why-do-i-get-error-cant-bind-to-items-since-it-isnt-a-known-property-of-ionic-selectable

**Comment by cerge** [comment]
Thanks! Is strange, it show me a error so i removed code and started again, compiled with : ionic cordova run android --device -l -c , and it show me the view with control, but nothing happens. Even, I see if it show me the console log when load the change event but no. Now, I started again the app on my mobile and it show me again the error : "Error: No provider for SelectSearchableComponent!" But i tried to fix all the things .Im using ionic 3, im not sure if maybe is the version of component

**Comment by petervarkoly** [comment]
Hi Evegnii
Now I've a similar issue. I'm using ionic-selectable in my project in more pages. This pages are used as Components for 
ModalController and they are working fine.

Now I want to use ionic-selectable in a normal page an I get the error:
core.js:10069 NG0303: Can't bind to 'items' since it isn't a known property of 'ion-selectable'.
https://github.com/petervarkoly/cranix-web/blob/d60c3f8037cd3b62d77a4999f36ddf60b6011b0b/src/app/protected/edu/lessons/tabs/room-control/room-control.component.html#L43

Do you have a hint for me?
