### ISSUE TITLE
Template for selected items/value

### ISSUE THREAD

**Issue by CatalinZoicas** [eakoriakin/ionic-select-searchable#26]
Hi,
I'm using the multi-select and after the ok i don't want tot display the picked items but the number of picked items. Is there a way to set it?
Thanks.

**Comment by edy-ap** [comment]
i help!

**Comment by eakoriakin** [comment]
@CatalinZoicas, @edy-ap, I've added this functionality as a part of `2.0.0` release:
https://github.com/eakoriakin/ionic-select-searchable/wiki/API-Documentation#value-template

There some breaking changes in `2.0.0`, please follow the [instructions](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.0.0) to update.
