### ISSUE TITLE
Keyboard automatically opens when using (onSearch), how can I avoid it and keep it close?

### ISSUE THREAD

**Issue by whyike** [eakoriakin/ionic-select-searchable#27]

**Comment by whyike** [comment]
Still waiting for an answer, someone can assist?

**Comment by eakoriakin** [comment]
Hi, I'll try look into it this week

**Comment by whyike** [comment]
Thanks man!! Waiting for it

**Comment by whyike** [comment]
any news regarding this issue, i'm standing a few days before planned release, maybe someone has any snippet for avoiding keyboard opening?

**Comment by bergist** [comment]
same here.

**Comment by eakoriakin** [comment]
Hey guys, sorry for a late response. I've added `focusSearchbar` parameter that use can use to enabled/disable the focus.
https://github.com/eakoriakin/ionic-select-searchable/wiki/API-Documentation#focussearchbar
