### ISSUE TITLE
Unable to Bind data comming from http post

### ISSUE THREAD

**Issue by glenngsanchez** [eakoriakin/ionic-select-searchable#29]
Hi, how do I bind data coming from http post?  

```
this.carmodels = [];
 this.getCarModels();

 this.carmodels.push({id:12,name:"Carmodel1"});
 this.carmodels.push({id:13,name:"Carmodel2"});
```

when logged the data in console, more data.  but select-searchable only shows the last 2 (Carmodel1, Carmodel2).

I tried moving the last 2 lines inside http success, and it does not show any data anymore.

Thanks

**Comment by eakoriakin** [comment]
Hey, `this.getCarModels()` is an asynchronous operation. You need to do the assignment inside callback.

```
this.getCarModels().subscribe(carmodels => {
    this.carmodels = carmodels;
});

**Comment by glenngsanchez** [comment]
Hi eakoriakin,

I updated my code and follow your sample source file.  I created an observable method like below:

```
function getCarModelsAsync(timeout=0):Observable<CarModelObj[]>{

    return new Observable<CarModelObj[]>(observer => {
      observer.next(this.getCarModels());
      observer.complete()
    }).pipe(delay(timeout));
 }
```
this.getCarModels() is getting data form http post.

and this sis how I called it:

```
this.getCarModelsAsync().subscribe(data =>{
      this.carmodels = data;
      console.log(this.carmodels);
    });
```
I notice some delay of fetching the data, and the list is still not showing.

Can you enlighten me more on this?

Thanks for the help.

**Comment by eakoriakin** [comment]
It works for me, can you show me your html for `<select-searchable>`?

**Comment by glenngsanchez** [comment]
This is my select-searchable
 

> <select-searchable  
>                     [isEnabled]="!isReadOnly"
>                     title="Model"
>                     [(ngModel)]="carmodel"
>                     [items]="carmodels"
>                     itemValueField="Id"
>                     itemTextField="ModelName"
>                     [canSearch]="true"
>                     (onChange)="modelChanged($event)">
>                 </select-searchable>

**Comment by eakoriakin** [comment]
Hi @glenngsanchez, did you manage to solve the issue?

**Comment by eakoriakin** [comment]
Closed for inactivity.
