### ISSUE TITLE
Suggestion - Minimum/Maximum selection

### ISSUE THREAD

**Issue by Newbie012** [eakoriakin/ionic-select-searchable#30]
It would be nice to compound the amount of selection. Something like:

    <select-searchable
          [title]="'global.fields.game.champions' | translate"
          [items]="gameData.champions"
          itemValueField="id"
          itemTextField="name"
          [canSearch]="true"
          [multiple]="true"
          **[minSelection]="number"**
          **[maxSelection]="number"**
        >
    </select-searchable>

**Comment by eakoriakin** [comment]
Hey, okay, so what you want is:
1. If the number of selected items isn’t in the min/max range then disable OK button.
2. Add a hint at the top of Select page so user can understand how many items he should choose and why OK button is disabled.
3. If only `min` parameter is set message should say “Select at least {min} item/s”.
4. If only `max` parameter is set message should say “Select {max} item/s maximum”.
5. If both `min` and `max` parameters are set message should say “Select between {min} to {max} items”.

Is that okay?

**Comment by Newbie012** [comment]
This is more than ok.

**Comment by eakoriakin** [comment]
@Hey @Newbie012, it has taken me a while to implement this feature, but it's done now 🙂 
Better late, than never, right? 👍 

Here is a demo:
https://stackblitz.com/edit/ionic-select-searchable-min-max-validation?file=pages%2Fhome%2Fhome.html
