### ISSUE TITLE
Multiples items are selected by default

### ISSUE THREAD

**Issue by Ralphkay** [eakoriakin/ionic-select-searchable#31]
Hi, first off most grateful for such an awesome plugin.

However, after installing everything, I realised that when a user clicks on an item to select just one, multiple items are selected at a time. I tried the [multiple]="false" feature on the API and it is still not working. 
Secondly, is there a way to tweak the styles, for instance, remove the radio buttons?

Thank you and once again biggups for such a great plugin!

**Comment by Ralphkay** [comment]
Hey, I have seen where the problem was. It had got to do with the [itemValueField]; once it was the same across the data set, the selection became multiple, irrespective of the [multiple] directive value set. Thanks.

**Comment by eakoriakin** [comment]
No problem 😆
