### ISSUE TITLE
Problem - Close Button

### ISSUE THREAD

**Issue by lucasamparo** [eakoriakin/ionic-select-searchable#33]
The close button doesn't appears in browser (S.O. windows 10).

![image](https://user-images.githubusercontent.com/5599946/39451026-a5ccef78-4ca3-11e8-82ca-ef70ea9731f8.png)

Someone knows how can I fix it?

**Comment by lucasamparo** [comment]
![image](https://user-images.githubusercontent.com/5599946/39451937-c9b8b57c-4ca6-11e8-9f99-5d00fd2a46c2.png)

Solved editing the source code from the plugin.

Modified the template, removing the "hide/show when" and add the icon built based on the platform selection in the construction of the app.

Someone have a better solution? Thanks.

**Comment by eakoriakin** [comment]
Hi, I’ll fix it on weekends, it seems easy

**Comment by akshaySMahendrakar** [comment]
Basically i see you have given **showwhen="android,windows"** and **showwhen="ios"**  how should i disable it and use it default.

**Comment by akshaySMahendrakar** [comment]
@lucasamparo what did you do to fix it?

**Comment by lucasamparo** [comment]
How can I send my version for the repository?

If the owner like the solution, maybe he will use and save some time...

**Comment by eakoriakin** [comment]
Hi guys, it's fixed in `ionic-select-searchable@1.1.2`.
