### ISSUE TITLE
Focus is automatically set when opening

### ISSUE THREAD

**Issue by CodeMatt17** [eakoriakin/ionic-select-searchable#34]
The focus should be configurable option on the following code:
```
    ngAfterViewInit() {
        if (this.searchbarComponent) {
            // Focus after a delay because focus doesn't work without it.
            setTimeout(() => {
                this.searchbarComponent.setFocus();
            }, 1000);
        }
    }
```
I don't want the focus to be set on the search bar when opening since it automatically displays the keyboard.

**Comment by eakoriakin** [comment]
Hi, I've added `focusSearchbar` parameter:
https://github.com/eakoriakin/ionic-select-searchable/wiki/API-Documentation#focussearchbar
