### ISSUE TITLE
stacked label 

### ISSUE THREAD

**Issue by vigalo** [eakoriakin/ionic-select-searchable#36]
Hello 

To keep the same UI styles, I need to use stacked labels with select-searchable?

It is possible?

Thanks.

**Comment by eakoriakin** [comment]
Hi @vigalo, it took me quite a bit of time, but now `ion-labels` are supported, both `stacked` and `floating`.
Have a look at the [2.7.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.7.0) release.
Please note that there're some breaking changes in `2.7.0` release.

**Comment by vigalo** [comment]
Hi @eakoriakin.
Thank you! It works like a charm!!

**Comment by ruisilva450** [comment]
Sorry, can you provide documentation for this?
The link you provided is dead

**Comment by eakoriakin** [comment]
Hey, no problem, I've updated the link:
https://stackblitz.com/edit/ionic-selectable-labels?file=pages%2Fhome%2Fhome.html
