### ISSUE TITLE
How set value using formBuilder?

### ISSUE THREAD

**Issue by danielfnz** [eakoriakin/ionic-select-searchable#4]
Hello, I'm trying to set value using formBuilder and the value not change on view.

I'm set te id of item on the form.

ex:   this.formulario.get('activity_id').setValue(this.activity_id);
![variedade](https://user-images.githubusercontent.com/6144301/36439367-12c35622-1643-11e8-915d-88a100dfc97d.jpg)

@eakoriakin

**Comment by eakoriakin** [comment]
Hey, you need to pass a whole object to control's `setValue()`, not only id.

```
// Say, there's a list of items - ports.
ports: Port[];
...
constructor(...) {
    this.ports = [{ id: 1, name: 'Vladivostok'}, { id: 2, name: 'Tokyo' }];

    // Value for Port control isn't set by default.
    this.portControl = this.formBuilder.control(null);
}

// Invoke this method at some point to set the value of Port control.
setPort() {
    let port = this.ports[1];

    // Passing whole object/port as value for control.
    this.portControl.setValue(port);
}
...
```

**Comment by danielfnz** [comment]
Thanks @eakoriakin.
This repository is helping me a lot.

**Comment by eakoriakin** [comment]
No problem, enjoy it 🙂

**Comment by danielfnz** [comment]
Its easy to add 'Item Creation' items not found?

**Comment by eakoriakin** [comment]
It might take a couple of days to implement "adding new items" functionality, but, unfortunately, I'm really busy these days. Can you create a new issue for it, and I'll try to implement it in the future.

**Comment by danielfnz** [comment]
Ok, I will try implement this feature. 
Thanks.

**Comment by viniciussvl** [comment]
Good e

> Hey, you need to pass a whole object to control's `setValue()`, not only id.
> 
> ```
> // Say, there's a list of items - ports.
> ports: Port[];
> ...
> constructor(...) {
>     this.ports = [{ id: 1, name: 'Vladivostok'}, { id: 2, name: 'Tokyo' }];
> 
>     // Value for Port control isn't set by default.
>     this.portControl = this.formBuilder.control(null);
> }
> 
> // Invoke this method at some point to set the value of Port control.
> setPort() {
>     let port = this.ports[1];
> 
>     // Passing whole object/port as value for control.
>     this.portControl.setValue(port);
> }
> ...
> ```

Good, thank you my friend! This work for me, your library is fantastic, one more time, thanks you.
