### ISSUE TITLE
scroll infinite - how to search which not fatched

### ISSUE THREAD

**Issue by rupendraa** [eakoriakin/ionic-select-searchable#40]
scroll infinite - how to search which not fatched

like if any text in last record - like entry  'Santa Cruz' on 44 no row
and search bar type without scroll search 'Santa Cruz' but its not show because scroll not done.

please correct that

**Comment by eakoriakin** [comment]
Hey, can you show me your code, so I could understand what you wanna to achieve exactly?

**Comment by eakoriakin** [comment]
Closed for inactivity.
