### ISSUE TITLE
not working on modal

### ISSUE THREAD

**Issue by akshaySMahendrakar** [eakoriakin/ionic-select-searchable#44]
the code is not working on the parent modal. basically i have a pop-up modal for registration and in registration i need a select country modal using select-searchable.

**Comment by wienzzz** [comment]
@eakoriakin sorry for commenting on closed topic, 

I used ionic-select-searchable inside modal with async search, it doesn't behave as expected (item not rendering correctly like below

![](https://im4.ezgif.com/tmp/ezgif-4-9bbaa10a76.gif)

**Comment by eakoriakin** [comment]
Hey, yes, async search doesn't work in a modal for some reason. I'll check it.

**Comment by wienzzz** [comment]
Just confirming that Filtering/searching on non-async item works fine.
Maybe problem with event emitter? or it refer to wrong component? (e.g: first modal?)

**Comment by eakoriakin** [comment]
Hey @wienzzz, @Patrick-Berg, I've fixed the issue in [2.6.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.6.0) release. Please, read the release notes as there's one breaking change.

Here's a [demo](https://stackblitz.com/edit/ionic-select-searchable-inside-modal?file=pages%2Fmodal%2Fmodal.ts).
