### ISSUE TITLE
ionic-selectable not working with ionic 7

### ISSUE THREAD

**Issue by gopikasingh** [eakoriakin/ionic-select-searchable#442]
Ionic-selectable does not seem to be working with ionic 7.
I tried installing all the 5.0.0 and above packages.
I keep getting the error (in app.module.ts) that
`Module '"ionic-selectable"' has no exported member 'IonicSelectableModule'.`

Is anyone else facing the same issue, and how can it be resolved?
Any help would be greatly appreciated.

**Comment by SimonFavraud** [comment]
I managed to use the plugin by downgrading to the 4.9.0 version

**Comment by Mersal-Mohamed2** [comment]
this happen to me and down grade to 4.9.0 
this error Module '"ionic-selectable"' has no exported member 'IonicSelectableModule'.
gone 
but i dont have any elements in the pop up only the header title 

this is my code 

`<ionic-selectable #selectableComponent [ngClass]="{'disabled': isDisabled}" [isEnabled]="!isDisabled"
  *ngIf="control && items" [formControl]="control" [items]="items" [itemValueField]="itemValueField"
  [shouldStoreItemValue]="shouldStoreItemValue" [itemTextField]="itemTextField + '_' + translationService.currentLang"
  [canSearch]="true" [isOnSearchEnabled]="true" [placeholder]="placeholder"
  closeButtonText="{{'Close' | translate}}" searchPlaceholder="{{'Search' | translate}}" (onSearch)="search($event)"
  [hasVirtualScroll]="true" virtualScrollApproxItemHeight="48px">

  <ng-template ionicSelectableSearchFailTemplate>
    <app-empty-list [label]="'No Items Found' | translate" fxFlex="nogrow"></app-empty-list>
  </ng-template>

  <ng-template ionicSelectableHeaderTemplate>
    <app-custom-header [enableGlobalLoading]="false" [title]="title" [endButtons]="endButtons">
      <ng-template #endButtons>
        <ion-buttons slot="start">
          <ion-button (click)="selectableComponent.close()">
            <ion-icon slot="icon-only" name="close"></ion-icon>
          </ion-button>
        </ion-buttons>
      </ng-template>
    </app-custom-header>
  </ng-template>

  <ng-template ionicSelectableValueTemplate let-value="value">
    {{items | arrayFind: itemValueField : value | translateField: itemTextField}}
  </ng-template>

  <ng-template ionicSelectableItemTemplate let-item="item">
    {{(item | translateField: itemTextField)}}
  </ng-template>

  <ng-template ionicSelectableFooterTemplate>
    <ion-toolbar>
      <ion-button fxFlex="nogrow" color="primary" size="large" shape="round" expand="block" fill="solid" strong="true"
        class="ion-margin" (click)="confirm()">
        {{'Confirm' | translate | titlecase}}
      </ion-button>
    </ion-toolbar>
  </ng-template>

  <ng-content></ng-content>
</ionic-selectable>`

**Comment by TheSakyo** [comment]
import with IonicSelectableComponent directly :
`import { IonicSelectableComponent } from 'ionic-selectable';`

if you're using ngModule, you'll need to import it in the 'declarations' or 'imports' section (i can't remember where to put it 😅); otherwise, if you're using standalone, you'll need to import it directly in the Component decorator in the 'imports' section.

**Comment by gopikasingh** [comment]
Thanks everyone, unfortunately I can't downgrade ionic-selectable as I'm using rxjs 7.5.0 and ionic-selectable is not compatible with that. 
I had found an alternative for it that perfectly works with ionic-7 and angular version 16.
Thanks for the responses!

**Comment by asad-96** [comment]
Is there any updated on this?

**Comment by asad-96** [comment]
So here is the solution.
- Don't import the` IonicSelectableModule ` anywhere in the module. 
- just use `IonicSelectableComponent` in page.module.ts.
- The version I'm using for ionic-7 is `"ionic-selectable": "^5.0.2",`
