### ISSUE TITLE
Missing "toLowerCase()" on filterItems method

### ISSUE THREAD

**Issue by victornoleto** [eakoriakin/ionic-select-searchable#45]
When you is searching any sentence, the plugin is not converting the key "itemTextField" from "[items]"  to lower case.

` items = this.selectComponent.items.filter(function (item) {
                    var /** @type {?} */ itemText = _this.selectComponent.itemTextField ?
                        item[_this.selectComponent.itemTextField] : item.toString().toLowerCase();
                    return itemText.indexOf(filterText_1) !== -1;
                });`

Suggestion: add "toLowerCase()" in line 195
` item[_this.selectComponent.itemTextField].toLowerCase();`

**Comment by eakoriakin** [comment]
Hi, just fixed it, try a new version `ionic-select-searchable@2.0.3`.

**Comment by eakoriakin** [comment]
@victornoleto let me know please, if the new version fixes your problem, so I could close the ticket.
