### ISSUE TITLE
modal is being disabled

### ISSUE THREAD

**Issue by emsdeveloper** [eakoriakin/ionic-select-searchable#46]
<img width="1066" alt="screen shot 2018-05-18 at 10 14 33 am" src="https://user-images.githubusercontent.com/31749714/40239576-6cb93f86-5a84-11e8-89f5-4d4fe2cfa42e.png">

I am having an issue with the modal. Clicking the X button in the top right corner works absolutely fine, but clicking outside, in the grayed out area, will disable it. The modal will close as expected, but then cannot be opened again unless you leave the page and come back.

**Comment by eakoriakin** [comment]
Hiey what version of `ionic-angular` do you use?

**Comment by eakoriakin** [comment]
Okay, I managed to reproduce it, will fix it soon.

**Comment by emsdeveloper** [comment]
Thanks for the quick response.

**Comment by eakoriakin** [comment]
Okay, I've fixed it in `ionic-select-searchable@2.0.4`.
Don't forget to star the repository 🙂

**Comment by emsdeveloper** [comment]
Thank you so much. It is now working correctly

**Comment by eakoriakin** [comment]
👍
