### ISSUE TITLE
debounce on async search

### ISSUE THREAD

**Issue by kodeine** [eakoriakin/ionic-select-searchable#48]
i think it will be a good idea to setup a debounce on user input while searching. I am using async and it hits the server on every keyword.

**Comment by eakoriakin** [comment]
Hey, good idea 👍

**Comment by eakoriakin** [comment]
Hey, I've added [searchDebounce](https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#searchdebounce) option in [2.0.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.2.0) release.
