### ISSUE TITLE
All items in list selected when selecting 1 item

### ISSUE THREAD

**Issue by remcogeldhof** [eakoriakin/ionic-select-searchable#49]
It all works perfect, I get the item that i have selected. But everytime I select an item, all items are selected. Although it always returns the selected item.
I don't know how to fix it.

 <select-searchable [(ngModel)]="exercise"
                           [items]="exerciseList"
                           itemValueField="id"
                           itemTextField="name"
                           [canSearch]="true"
                           multiple="false"
                           (onChange)="portChange($event)" formControlName="search">

**Comment by remcogeldhof** [comment]
Found it, id wasn't named id but excerciseId.
Thank you, it's working very nice :)

**Comment by eakoriakin** [comment]
@remcogeldhof no problem, star the project please if it's useful for you 🙂
