### ISSUE TITLE
Property '_valueItems' is private and only accessible within class 'SelectSearchableComponent'. AOT build

### ISSUE THREAD

**Issue by janstrbik** [eakoriakin/ionic-select-searchable#51]
I tried --prod --aot build in my ionic app with this plugin, but I am getting these errors:

`Error at myProject/node_modules/ionic-select-searchable/ionic-select-searchable.d.ts.SelectSearchableComponent.html(7,18): Property '_valueItems' is private and only accessible within class 'SelectSearchableComponent'.`

`Error at myProject/node_modules/ionic-select-searchable/ionic-select-searchable.d.ts.SelectSearchableComponent.html(12,17): Property '_valueItems' is private and only accessible within class 'SelectSearchableComponent'.`

`Error at myProject/node_modules/ionic-select-searchable/ionic-select-searchable.d.ts.SelectSearchablePageComponent.html(8,26): Type 'TemplateRef<any>' is not assignable to type 'boolean'.`

I have installed latest version of plugin `2.2.1`. Can you please solve it in your plugin?

**Comment by eakoriakin** [comment]
Hey, I just tried `ionic cordova build android --prod --aot` on [demo repo](https://github.com/eakoriakin/ionic-select-searchable-demo) and the build was successful.

By any chance, are you trying to use private `_valueItems` field?

**Comment by janstrbik** [comment]
Sorry my mistake, I tried it with this: `ionic cordova build android --prod --release --aot --minifyjs --optimizejs --minifycss`

Can you try this too? And no I am not trying use private properties, I am using your plugin only like this:
`<select-searchable [(ngModel)]="timezone" title="Timezone" [items]="timeZoneList" itemValueField="TimeZoneId" itemTextField="Description" [canSearch]="true" (onChange)="timeZoneChange($event)" searchPlaceholder="Search"></select-searchable>`

**Comment by eakoriakin** [comment]
Hmm, tried same `ionic cordova build android --prod --release --aot --minifyjs --optimizejs --minifycss` on [demo repo](ionic cordova build android --prod --release --aot --minifyjs --optimizejs --minifycss) and it also worked.

Can you create a small repo where I could reproduce the error?

**Comment by eakoriakin** [comment]
Close for inactivity.
