### ISSUE TITLE
Show Search with dropdown section on load of screen

### ISSUE THREAD

**Issue by jishadp** [eakoriakin/ionic-select-searchable#55]
Hi Guys,

I am integrated this package and its very usefull and working perfect. In my current situation, the location selection is showing on the top of the screen.

On loading the page, I need to load the search section of select searchable. which means automatically open the search box..(Dynamically open the search selecteble on load other than taping on screen).

Please help me how  to make it with this package.

**Comment by eakoriakin** [comment]
Hey, try to use [open()](https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#open) method.

And don't forget to star the project 🙂 👍
