### ISSUE TITLE
Add VirtualScroll

### ISSUE THREAD

**Issue by kyleabens** [eakoriakin/ionic-select-searchable#56]
Requesting to add Ionics VirtualScroll capabilities to the select-searchable component.

https://ionicframework.com/docs/api/components/virtual-scroll/VirtualScroll/

**Comment by eakoriakin** [comment]
Hey @kyleabens, I've implemented VirtualScroll in the latest [2.4.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.4.0) release.
