### ISSUE TITLE
Display Image on Results Window

### ISSUE THREAD

**Issue by kodeine** [eakoriakin/ionic-select-searchable#57]
Hello,
I wanted to know how can i display flag in the listing? Can i define the template of the select items?

![image](https://user-images.githubusercontent.com/8620059/40878366-ba48d428-6655-11e8-9e63-cf6df14cd864.png)

**Comment by eakoriakin** [comment]
Yes you can, use [item template](https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#item-template) or [item right template](https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#item-right-template).

Demo:
https://stackblitz.com/edit/ionic-select-searchable-item-right-template?file=pages/home/home.html
