### ISSUE TITLE
Target of ngModel is filled with reference to chosen object, instead of just value of itemValueField of that object.

### ISSUE THREAD

**Issue by alenl** [eakoriakin/ionic-select-searchable#58]
Hi, first of all, fantastic component!
I'm trying to use this as a swap-in replacement for ion-select, however the behavior of ngModel and item value is very different. In ion-select, the value of the "value" attribute of is set into the ngModel target variable. With select-searchable , however, the reference to the _entire object_ is stored there. This discrepancy is complicating the replacement significantly. 

Is there a way to make it store the actual "value" into the model, not reference to the holder object?

Here's an example:

```

...
protected foundProductId1: number;
protected foundProductId2: number;
protected products = [ { _id: 1, name: "apple"}, { _id: 2, name: "orange" } ]
```

```
<ion-select [(ngModel)]="foundProductId1">
     <ion-option *ngFor="let p of products" value="{{p._id}}">{{p.name}}</ion-option>
</ion-select> 

<select-searchable
    [(ngModel)]="foundProductId2"
    [items]="products"
    itemValueField="_id"
    itemTextField="name"
    [canSearch]="true">
</select-searchable>
```

If I select the "apple" in both, the results will be:
foundProductId1=1
  but
foundProductId2= { _id:1, name:"apple" } 

Any idea on how to work around it without changing all the surrounding code logic? Thanks!

**Comment by eakoriakin** [comment]
Hey, okay, I see you problem. Storing the whole object is the intended behavior, however I can add a parameter like `shouldStoreItemValue` to make it similar to `ion-select`. I’ll try to do it soon

**Comment by alenl** [comment]
That's perfect. Anything I can do to help?

**Comment by alenl** [comment]
Hi @eakoriakin , this now works, thanks! 
I've noticed it now requires selectSearchableValueTemplate with a find function. If that is not provided, then it doesn't show the name of selected value next to the label (when the search is not open). I'm wondering... if it can show the name of each item correctly in the list without this, why is it required to show the name in the base component display? 
Sorry if I'm nagging, but I'd really like to have this as a replacement for ion-select. :)

**Comment by eakoriakin** [comment]
Ah, common 🙂

**Comment by eakoriakin** [comment]
Okay, I'll add this later

**Comment by eakoriakin** [comment]
If you star the project 🙂

**Comment by alenl** [comment]
Hah - but I already did, didn't I? :)

**Comment by eakoriakin** [comment]
Okay, so value is formatted in `select-searchable.component.ts`:
```
<div class="select-searchable-value-item" *ngFor="let valueItem of _valueItems">
    {{_formatItem(valueItem)}}
</div>
````

**Comment by eakoriakin** [comment]
@alenl hey, I'll have some free time these weekends, so I can implement this feature, if you haven't done it yet.

**Comment by alenl** [comment]
Sorry, I didn't have a chance to get to it yet. If you can do it, even better. I'm not sure if I would get to that in the next week or two due to other obligations.

**Comment by eakoriakin** [comment]
I worries, I’ll do it.

**Comment by eakoriakin** [comment]
Hey @alpeshvasani, I've implemented the desired behavior in [2.7.2](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.7.2) version.

**Comment by martinlombana** [comment]
Hi, 

There is something I don't understand. Given this array of objects:

```
[{ 
name: 'American Samoa',
code: 'AS'
},{
name: 'American Samoa',
code: 'AD'
},
}
 ]
```

`						<ionic-selectable #authSelect
						
						                  item-content
						                  formControlName="country"
						                  [items]="country_list"
						                  itemValueField="name"
						                  itemTextField="name"
						                  [canSearch]="true"
						                  [isMultiple]="false"
						                  [shouldStoreItemValue]="false"
						                  confirmButtonText="Select"
						                  label="Country"
						                  >
							
							<ion-title>
								Country
							</ion-title>
						</ionic-selectable>`

When American Samoa is selected, ionic-slectable stills stores this in the form value:
![image](https://user-images.githubusercontent.com/18351919/55428423-5e26ea80-5589-11e9-9adb-20e1c2e2fbe3.png)

While it should be just storing "Andorra".

shouldStoreItemValue, should store JUST the value itself. Not an object with JUST that value.

Unless I am missing something, this is wrong. While I can do re-parsing after, I would like to avoid that so I can use this component with automated setups. 

Thanks,

**Comment by techvipers** [comment]
https://stackblitz.com/edit/ionic-select-searchable-should-store-item-value?file=pages%2Fhome%2Fhome.html

This demo link is dead. Can you provide a working project on stackblitz for demo
