### ISSUE TITLE
How dev this package?

### ISSUE THREAD

**Issue by danielfnz** [eakoriakin/ionic-select-searchable#6]
Hello, I did the fork this package, commited changes, run gulp to build and send push changes to my fork.

So, when I add my fork to my project, the files "are same of the repo, and the dist files dont show".

If I'm copy the dist files and put on npm_modules/ionic-select-searchable the changes works same times.
 
My question is : How to download dist files when run npm install git://github.com/danielfnz/ionic-select-searchable.

**Comment by eakoriakin** [comment]
If you fixed an issue or added some functionality, you can create a pull request so I could upload a new package version to npm. What do you want to do?
