### ISSUE TITLE
Change labelling size

### ISSUE THREAD

**Issue by wienzzz** [eakoriakin/ionic-select-searchable#60]
@eakoriakin is there any way to change size of the label?

if I use icon as the label like my code
```
<ion-item>
                  <select-searchable formControlName="agen"
                      [items]="_agents"
                      itemValueField="id_agen"
                      itemTextField="nm_agen"
                      [hasVirtualScroll]="true"
                      [canSearch]="true"
                      (onChange)="agentChange($event)">
                      <ng-template selectSearchableLabelTemplate>
                          <ion-icon name="person"></ion-icon>
                      </ng-template>
                  </select-searchable>
              </ion-item>
```

The size is distributed evenly between label and value which make it unappealing for user

![screenshot from 2018-06-16 17-18-57](https://user-images.githubusercontent.com/17917649/41497895-684799fe-7189-11e8-8b28-ad094345af2b.png)

**Comment by eakoriakin** [comment]
Yes, just change the width of the label element:
https://image.prntscr.com/image/gsonjQC6SnWFDclvdSn7rg.png

**Comment by wienzzz** [comment]
Okay thanks
