### ISSUE TITLE
Label font color, arrow down

### ISSUE THREAD

**Issue by condepatula** [eakoriakin/ionic-select-searchable#61]
Hello!
1. The label font color is black and not grey
2. The arrow down is not visible
![a_3](https://user-images.githubusercontent.com/5973066/41628236-9dbad442-73f1-11e8-940f-d2146baf8050.png)
![a_2](https://user-images.githubusercontent.com/5973066/41628237-9de4142e-73f1-11e8-9f44-1ebfb776d73d.png)
![a_1](https://user-images.githubusercontent.com/5973066/41628238-9e5d4696-73f1-11e8-81c5-08d4c80cdff0.png)

Thanks!

**Comment by eakoriakin** [comment]
Hey, what is this environment?

**Comment by condepatula** [comment]
Hello!

>ionic info

cli packages: (C:\Users\Miguel\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.3
    npm  : 4.3.0
    OS   : Windows 8.1

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

>cordova info
Collecting Data...


Node version: v8.11.3

Cordova version: 8.0.0

**Comment by eakoriakin** [comment]
It might have something to do with `Ionic View`. Are styles correct if you run the app in a browser with `ionic serve`?

**Comment by eakoriakin** [comment]
Closed for inactivity.
