### ISSUE TITLE
NgModal Change is not getting reflacted

### ISSUE THREAD

**Issue by alpeshvasani** [eakoriakin/ionic-select-searchable#62]
When I change the value of NgModel variable with one of the values present in item[] it is not displaying on the select menu that this item is selected.

**Comment by eakoriakin** [comment]
Hey, can you post your code here, so I could have a look?

**Comment by alpeshvasani** [comment]
```
            this.items.forEach((item, index) => {
              if (item.name == this.itemName) {
                this.itemName = this.items[index];
              }
            });
```
This worked.
