### ISSUE TITLE
Select search list is not displaying well

### ISSUE THREAD

**Issue by alpeshvasani** [eakoriakin/ionic-select-searchable#64]
The list of item in the select menu is not displaying item having large length. Also after selecting it value fields goes out of the screen. I tried many ways to overwrite CSS and get ellipsis but failed.
<img width="219" alt="screenshot 4" src="https://user-images.githubusercontent.com/26425141/41829992-b182b882-785b-11e8-8ea8-1fc7fbd48399.png">

<img width="387" alt="screenshot 5" src="https://user-images.githubusercontent.com/26425141/41829993-b1b54bf8-785b-11e8-9442-87c17096a774.png">

<img width="465" alt="screenshot 6" src="https://user-images.githubusercontent.com/26425141/41829994-b1e54420-785b-11e8-9c6f-2f649651a24f.png">

<img width="237" alt="screenshot 7" src="https://user-images.githubusercontent.com/26425141/41829995-b2123692-785b-11e8-8f2e-12c4e3877177.png">

**Comment by eakoriakin** [comment]
Hi, show me a code sample please. Also, what version of ionic-select-searchable do you use?

**Comment by wienzzz** [comment]
wasn't this the expected behaviour? using ion-select with longer text will give similar results

what did you expect? 
are you expecting text-wrap around longer text?

**Comment by eakoriakin** [comment]
Hey @alpeshvasani, I fixed overflow issues. Just update to [2.7.2](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.7.2) version.
```
npm i ionic-select-searchable@2.7.2
```
