### ISSUE TITLE
How to fix error property 'startsearch' does not exist on type 'select searchable component

### ISSUE THREAD

**Issue by cokcok** [eakoriakin/ionic-select-searchable#65]
How to fix error property 'startsearch' does not exist on type 'select searchable component

**Comment by eakoriakin** [comment]
Also, check out this demo on how to use `startSrarch()` method:
https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#startsearch

**Comment by cokcok** [comment]
thank you
