### ISSUE TITLE
I want your blog address, is it convenient to tell me?

### ISSUE THREAD

**Issue by wenxiayili** [eakoriakin/ionic-select-searchable#66]
Such a good component, such a good programming skills, please tell me your blog address bar! I want to learn!

**Comment by eakoriakin** [comment]
Hey @wenxiayili, I don't have one, sorry 🙁

**Comment by eakoriakin** [comment]
@wenxiayili if you wanna learn JavaScript, then checkout this book - [Secrets of the JavaScript Ninja](https://www.manning.com/books/secrets-of-the-javascript-ninja). It really helped to improve my skills and understand the core principals of JS.
