### ISSUE TITLE
Set placeholder instead of label (enhancement)

### ISSUE THREAD

**Issue by kyleabens** [eakoriakin/ionic-select-searchable#68]
I would love to have the ability to set the title of the searchable component as a placeholder and not ion-label.  All of my other inputs including ion-selects use placeholders.

**Comment by granttink** [comment]
+1

**Comment by eakoriakin** [comment]
Hey guys, I added [placeholder](https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#placeholder) field and [placeholderTemplate](https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#placeholder-template) in [2.7.3](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.7.3) release.
Here's a demo - [ionic-select-searchable-placeholder](https://stackblitz.com/edit/ionic-select-searchable-placeholder?file=pages%2Fhome%2Fhome.html).
Enjoy 😉

PS: Don't forget to **star** the project, if you haven't yet and tell all your friends about it 🙂

**Comment by kyleabens** [comment]
You the man, thank you!
