### ISSUE TITLE
Erro on use 

### ISSUE THREAD

**Issue by MiqueM** [eakoriakin/ionic-select-searchable#7]
Hi, 
I receive this error:

1. If 'select-searchable' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by eakoriakin** [comment]
Hey, are you using lazy loading by any chance?
If you are, try importing SelectSearchable to each "lazy" page module.

```
import { LazyPage } from './lazy';
import { SelectSearchableModule } from 'ionic-select-searchable';

@NgModule({
	declarations: [
		LazyPage
	],
	imports: [
		IonicPageModule.forChild(LazyPage),
		SelectSearchableModule
	]
})
export class LazyPageModule { }
```
