### ISSUE TITLE
Select text value only visible after second time selecting

### ISSUE THREAD

**Issue by elmartino** [eakoriakin/ionic-select-searchable#75]
Hi, Thanks for the great plugin. I have a strange situation:

The selected value is only visible after the second time i select the item in the list.

This is only for my 'dynamic loaded items', if i use the example (port) it's working as expected.

Any ideas?

`        <ion-item>
            <ion-label stacked>Other Coin
                <span *ngIf="tickerOther" style="font-size:11px;">(Last bid: {{tickerOther.Bid}})</span>
            </ion-label>
            <select-searchable item-content [ngModel]="config.otherCoin" [items]="markets" itemValueField="MarketName" itemTextField="MarketName"
                [canSearch]="true" (ngModelChange)="onChangeOtherCoin($event)">
            </select-searchable>
        </ion-item>`

**Comment by eakoriakin** [comment]
Hey, what if you remove `*ngIf`, does it work?
Can you prepare a small demo like [this](https://stackblitz.com/edit/ionic-select-searchable-basic?file=pages%2Fhome%2Fhome.html) on StackBlitz with your problem?

**Comment by elmartino** [comment]
The problem was me setting the model value 'again' in the onChange function. Thanks!
