### ISSUE TITLE
in IOS, search only working for first 2 typed characters

### ISSUE THREAD

**Issue by elmartino** [eakoriakin/ionic-select-searchable#76]
Hi, 

When searching in iOS app (ionic cordova run ios), it's only looking for the first 2 typed characters. So if i type: ST for example, it finds the item 'BTC-STRAT'. If i type STR, no results are found. The same app in Safari  on the same device is working without a problem.

Any ideas?

Thanks!

**Comment by elmartino** [comment]
After removing and readding ios platform it works as expected.

**Comment by eakoriakin** [comment]
👍
