### ISSUE TITLE
2.8.0 Typescript error when building with --prod flag

### ISSUE THREAD

**Issue by kyleabens** [eakoriakin/ionic-select-searchable#78]
I get the following error when I go to build my ionic app for production with version 2.8.0

<img width="424" alt="screen shot 2018-07-19 at 10 47 06 pm" src="https://user-images.githubusercontent.com/25699262/42980519-b75b3aba-8ba5-11e8-8590-dc025c725110.png">

**Comment by eakoriakin** [comment]
Hey, shit, you are right, there's was in issue in the way I build the component. Try `2.8.1` version.

**Comment by kyleabens** [comment]
All is working well with 2.8.1, thank you!

I was having problems populating the searchable component with data I was receiving from a promise.  I kept getting a 'length is undefined' error.  For those who run into the same issue it's due to the (onSearch) event.  I had to run event.component.endSearch() and event.component.enableInfiniteScroll() both outside of the promise and when the promise resolves.  Example:

```
searchMakes(event) {

    this.pageNum = 0;

    this.index.search({
      query: event.text.trim().toLowerCase(),
      hitsPerPage: 50,
      page: this.pageNum
    }).then(content => {
        event.component.items = content.hits;
        event.component.endSearch();
        event.component.enableInfiniteScroll();
      }
    }).catch(err => console.log(err));

    event.component.endSearch();
    event.component.enableInfiniteScroll();
  }
```
