### ISSUE TITLE
Custom close icon (enhancement)

### ISSUE THREAD

**Issue by kyleabens** [eakoriakin/ionic-select-searchable#79]
I know we are able to pass text for the close button on ios but it'd be great if we could pass something like `<span class="fa fa-close"></span>` if we are using some sort of external icon library.  Not sure how difficult this would be to implement but if it's too much of a hassle you can just close this.

**Comment by eakoriakin** [comment]
It shouldn’t be a big deal, I’ll have a look

**Comment by kyleabens** [comment]
Works like a charm!  Thank you!
