### ISSUE TITLE
Clickable text search string

### ISSUE THREAD

**Issue by CoreyReynolds** [eakoriakin/ionic-select-searchable#81]
Hello,

Creating the following issue per your request from the forum post I made earlier:

------------------------------------------------------------------
Excellent tool, I’ve integrated it into my project - thank you for all your work.
I’ve used it to search for street names.
One thing our design department wants, is once a street is typed in, if it doesn’t exist they would like a search item to appear in the list that says “Create [search text]” (which can then be clicked to launch an event to add that item to the list and select it…)

Using your product, would you recommend a way to implement this? The “create [search text]” item showing up, specifically.

**Comment by eakoriakin** [comment]
Hey @CoreyReynoldsm, it's now possible. 

`npm i ionic-select-searchable@2.10.0`

Use cases:
- [Adding, editing and deleting items](https://stackblitz.com/edit/ionic-select-searchable-add-item?file=pages/home/home.html)
- [Adding, editing and deleting items asynchronously](https://stackblitz.com/edit/ionic-select-searchable-add-item-async?file=pages/home/home.html)
- [Adding item when search fails](https://stackblitz.com/edit/ionic-select-searchable-add-item-on-search-fail?file=pages/home/home.html)
- [Adding item asynchronously when search fails](https://stackblitz.com/edit/ionic-select-searchable-add-item-on-search-fail-async?file=pages/home/home.html)

Please note that there are some breaking changes in [2.10.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.10.0) release.
