### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jjsosa** [eakoriakin/ionic-select-searchable#82]
Hello!
I'm trying to use the component with Multiple Selection, InfiniteScroll and Search, but when I insert the onSearch() option in the html I'm always seeing this error: "Cannot read property 'length' of undefined".

This is my element in the html file:
```
<select-searchable
    #professionComponent
    item-content
    [(ngModel)]="selectedProfessions"
    formControlName="professions"
    itemValueField="id_profession"
    itemTextField="name_profession"
    [items]="professions"
    [canSearch]="true"
    (onSearch)="searchProfs($event)"
    [isMultiple]="true"
    [isOkButtonEnabled]="professionComponent.itemsToConfirm.length >= 1 && professionComponent.itemsToConfirm.length <= 3"
    (onChange)="changeProfession($event)"
    [hasInfiniteScroll]="true"
    (onInfiniteScroll)="getMoreProfs($event)">
    <ng-template selectSearchableMessageTemplate>
        Selecciona máximo 3 profesiones
    </ng-template>
</select-searchable>
```
I have got defined all the methods for "onSearch", "onChange" and "onInfiniteScroll" in the .ts file (3 different calls to the API to refresh the list).
I detected that if I delete the (onSearch)="searchProfs($event)" my code runs well without errors.
I suppose the error is in the "onSearch" method.

How can I use Multiple Selection, InfiniteScroll and Search in the same component? Am I doing something wrong? Or the component doesn't runs if trying all these options together?

Thanks in advance!

**Comment by kodeine** [comment]
same issue here.

**Comment by CoreyReynolds** [comment]
Yeah this is happening for me as well. I just updated to the newest version and it broke all of mine that use an OnSearch field.

**Comment by eakoriakin** [comment]
Guys, there were breaking changes in [2.8.1](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.8.1) version:

- Removed `infiniteScroll` parameter from `onInfiniteScroll` and `onSearch` events. To update follow the steps below. Check out the [demo](https://stackblitz.com/edit/ionic-select-searchable-infinite-scroll?file=pages%2Fhome%2Fhome.html) as well.
1. Replace `event.infiniteScroll.enable(true);` with `event.component.enableInfiniteScroll();`.
2. Replace `event.infiniteScroll.enable(false);` with `event.component.disableInfiniteScroll();`.
3. Replace `event.infiniteScroll.complete();` with `event.component.endInfiniteScroll();`.

**Comment by CoreyReynolds** [comment]
I am not using infinitescroll in my project.

**Comment by eakoriakin** [comment]
For `onSearch` event you also need to use `event.component.endSearch()` and `event.component.endSearch()` as shown here:
https://stackblitz.com/edit/ionic-select-searchable-on-search?file=pages%2Fhome%2Fhome.ts

**Comment by CoreyReynolds** [comment]
Ah, thanks.

**Comment by eakoriakin** [comment]
@jjsosa can you show me your `.ts` file?

**Comment by kodeine** [comment]
@eakoriakin i've updated the methods but i still get 

```
Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
```

**Comment by eakoriakin** [comment]
@jjsosa a combination `onSearch`, `onInfiniteScroll` and `onChange` is possible and seems to work fine in this [demo](https://stackblitz.com/edit/ionic-select-searchable-infinite-scroll-is-multiple?file=pages%2Fhome%2Fhome.html).

Also, I noticed that you are using both `ngModel` and `formControlName`  in your HTML sample. It should be one of them, not both at the same time.

**Comment by jjsosa** [comment]
Even deleting `ngModel`, still say `Cannot read property length of undefined`

**Comment by jjsosa** [comment]
I have got this select-searchable component inside an angular form, and I'm trying to validate that you selected 1 to 3 professions that are in the list. We have got a lot of professions and I need the InfiniteScroll, Search and Multiple Selection.
I saw all your examples and every of them just use 1 of that methods, not all together. And it's all running except when I add the "(onSearch)=..." in the HTML.

**Comment by janneskoehler** [comment]
Same issue here.
I think the _filteredGroups are not set to empty array.

Error:
`TypeError: Cannot read property 'length' of undefined
    at Object.eval [as updateDirectives] (SelectSearchablePageComponent.html:1)`

I had a look to the SelectSearchablePageComponent.html:1 and found:
`<ion-list no-margin *ngIf="!selectComponent.hasVirtualScroll && selectComponent._filteredGroups.length">`

My Setup:
`<select-searchable *ngIf="this.items?.length > 500" item-content itemValueField="id" itemTextField="name" [(ngModel)]="this._initValue" [items]="first50Items" [canSearch]="true" (onChange)="this.event($event)" [isEnabled]="!this.viewingMode" (onSearch)="searchItems($event)" noItemsFoundText="Bitte geben Sie einen (anderen) Suchbegriff ein." searchDebounce="500" searchPlaceholder="Suche">
  </select-searchable>`

**Comment by eakoriakin** [comment]
Guys, can you share a demo with your issue, so I could reproduce it?

**Comment by eakoriakin** [comment]
@janneskoehler, do you need `this.` in your template? I think it shouldn’t be used in a template

**Comment by CoreyReynolds** [comment]
I feel like the most common issue here with errors or irregular data either comes from not surrounding your search in startsearch and endsearch, and not assigning the new filtered list of items to the event.component.items. Just a couple things to check first.

**Comment by janneskoehler** [comment]
@eakoriakin, you are right, but that does not solve the issue.
I fixed my issue by changing `_filteredGroups: any[];` to `_filteredGroups: any[] = [];` in select-searchable.component.ts

**Comment by eakoriakin** [comment]
Thanks for investigating it ;) can you share your ts file so I could get an idea of what’s going on?

**Comment by eakoriakin** [comment]
@janneskoehler I've added `_filteredGroups: any[] = [];`.

**Comment by ashish-patidar-rau** [comment]
> Guys, there were breaking changes in [2.8.1](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.8.1) version:
> 
> * Removed `infiniteScroll` parameter from `onInfiniteScroll` and `onSearch` events. To update follow the steps below. Check out the [demo](https://stackblitz.com/edit/ionic-select-searchable-infinite-scroll?file=pages%2Fhome%2Fhome.html) as well.
> 
> 1. Replace `event.infiniteScroll.enable(true);` with `event.component.enableInfiniteScroll();`.
> 2. Replace `event.infiniteScroll.enable(false);` with `event.component.disableInfiniteScroll();`.
> 3. Replace `event.infiniteScroll.complete();` with `event.component.endInfiniteScroll();`.

thanks i have solve my issue
