### ISSUE TITLE
Template to search multiple fields

### ISSUE THREAD

**Issue by TrevorLinkgreen** [eakoriakin/ionic-select-searchable#84]
I am attempting to search on multiple fields, (SKU -OR- description), but it seem to only ever search on the itemTextField

It properly shows the template when searching, but just doesn't allow you to search on the SKU

```
  <ion-item>
    <ion-label>SKU</ion-label>
    <select-searchable item-content [items]="supplierItems" itemValueField="ItemId" itemTextField="Description" [canSearch]="true">
      <ng-template selectSearchableTitleTemplate>
        SKU
      </ng-template>
      <ng-template selectSearchableItemTemplate let-item="item">
        ({{item.SKU}}) {{item.Description}}
      </ng-template>
    </select-searchable>
  </ion-item>

```

Is there a way to make ionic-select-searchable search on multiple fields?

Thanks in advance (great plugin)

**Comment by eakoriakin** [comment]
Hello @TrevorLinkgreen. The component doesn't know anything about your search logic and the templates simply renders your items.
However, you can implement any search functionality in your `onSearch` event.
Here's how:
https://stackblitz.com/edit/ionic-select-searchable-on-search?file=pages%2Fhome%2Fhome.html

**Comment by TrevorLinkgreen** [comment]
Perfect, thanks
