### ISSUE TITLE
placeholder template

### ISSUE THREAD

**Issue by kodeine** [eakoriakin/ionic-select-searchable#86]
@eakoriakin template placeholder is not showing placeholder.

i'm using the following but placeholder is not visible.
```
<ng-template selectSearchableTitleTemplate>
            Port
        </ng-template>
        <ng-template selectSearchablePlaceholderTemplate>
            Port <span style="color: white;">(Dry)</span>
        </ng-template>
```

**Comment by eakoriakin** [comment]
Hey, it should work fine unless you have something assigned to `ngModel` or `formControl`.
Have a look at this [demo](https://stackblitz.com/edit/ionic-select-searchable-placeholder?file=pages%2Fhome%2Fhome.html).
If this doesn't help then put your code on [StackBlitz](https://stackblitz.com) so I could reproduce the issue.

**Comment by eakoriakin** [comment]
Closed for inactivity.
