### ISSUE TITLE
Launch selection programatically

### ISSUE THREAD

**Issue by CoreyReynolds** [eakoriakin/ionic-select-searchable#91]
Hi,

Just finishing a couple things with an app using your component. Just a couple thing which may be possible (but maybe I'm missing how to use) - is there a way to launch the selection programatically (from say, another button)? I tried launching using 
`    let element: HTMLElement = document.getElementById('PublicComment') as HTMLElement;
    element.click();`
click doesn't seem to go anywhere.

Also, (and I'll make another issue if you would prefer) - is it possible to add a button to the row for an item that doesn't have pass-through propagation? (was going to add a pin/unpin button).

**Comment by eakoriakin** [comment]
Hey, you can open select page with open() method, check Documentstion in Wiki to see a demo.

Not sure what you mean by propogation in this case, but do have a look at itemsToConfirm option in the docs.

**Comment by CoreyReynolds** [comment]
You end up answering a lot of questions that are less "how do I use your tool" and more "how do I use **a** tool. Thanks again for the help :)
A bit new to the environment and sometimes it's hard to tell where to look for solutions. Cheers.

**Comment by eakoriakin** [comment]
No problem ;)
